### ISSUE TITLE
你好，请问可以开放训练代码么，十分感谢！

### ISSUE THREAD

**Issue by QSLee-Net** [cqu20160901/UNetMutilLane_onnx_tensorRT_rknn_horizon#5]
如果有时间方便看到我的问题，请问下什么时候可以开放下训练代码，瞻仰学习下。或者留个联系方式，学习交流。谢谢，盼复！

**Comment by cqu20160901** [comment]
训练代码目前是基于项目用的代码改的，不是很方便拿出来开源，晚点我重新写一个简化版的训练代码再开源。不过可以加个联系方式交流学习，微信搜索1013429609。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月22日(周三) 下午5:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cqu20160901/UNetMutilLane_onnx_tensorRT_rknn_horizon] 你好，请问可以开放训练代码么，十分感谢！ (Issue #5)




 
如果有时间方便看到我的问题，请问下什么时候可以开放下训练代码，瞻仰学习下。或者留个联系方式，学习交流。谢谢，盼复！

**Comment by cqu20160901** [comment]
训练代码 https://github.com/cqu20160901/UNetMultiLane
